### ISSUE TITLE
Add a command to tag a release

### ISSUE THREAD

**Issue by jaraco** [coherent-oss/coherent.cli#6]
In the [skeleton project](/jaraco/skeleton), a new release is cut by running `tox -e finalize`, which consolidates changelog entries in a new commit and tags that commit.

As of yet, there is no support in the Coherent System for a changelog, so the finalize command doesn't make sense. Moreover, since there's no changelog, there's no set of changes from which to infer the version bump.

I'm considering adding a command `coh tag {major,minor,patch}` that will create the tag for the relevant patch level, rather than require the user to list the current tags and perform the calculation.

**Comment by johnslavik** [comment]
However, let's keep the possibilty of specifying absolute tags, for instance in order to be able to release alpha/beta/RC/post versions.

**Comment by jaraco** [comment]
Right. Nothing would prevent a manual tag. Just a convenience tool when making a typical release.
